name: d94
recipe: drupal9
excludes:
  - node_modules
services:
  database:
    type: mariadb:10.3
  node:
    type: "node:16"
    scanner: false
    ssl: true
    sslExpose: false
    globals:
      gulp-cli: latest
    overrides:
      ports:
        - "32654:32654"
  appserver:
    build:
      - composer install
    xdebug: true
    config:
      php: lando/config/php.ini
    type: php:8.1
    overrides:
      environment:
        DRUSH_OPTIONS_URI: "http://d94.lndo.site"
  # (optional) Install Mailhog service for testing emails sent from Drupal.
  # No addl. config required elsewhere to use; SMTP contrib is not required.
  mailhog:
    type: mailhog
    portforward: false
    hogfrom:
      - appserver
config:
  composer_version: 2-latest
  via: nginx
  database: mysql:5.7
  webroot: ./web
  php: 8.1
  xdebug: true
  config:
    php: lando/config/php.ini

# Add additional tooling
tooling:
  node:
    service: node
  npm:
    service: node
  npx:
    service: node
  gulp:
    service: node
    dir: "/app/web/themes/custom/vote_gov"
    cmd: gulp watch
  gulp-compile:
    service: node
    dir: "/app/web/themes/custom/vote_gov"
    cmd: gulp compile
  build:
    description: "Install NPMs"
    cmd:
      - node: "/app/lando/build/theme.sh"
  xoff:
    cmd: "rm /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && /etc/init.d/apache2 reload"
    description: Disable xdebug.
    service: appserver
    user: root
  xon:
    cmd: "docker-php-ext-enable xdebug && /etc/init.d/apache2 reload"
    description: Enable xdebug.
    service: appserver
    user: root
  phpcs:
    service: appserver
    cmd: "/app/vendor/bin/phpcs --standard=Drupal --extensions='php,module,inc,install,test,profile,theme,js,css,info,txt'"
  # Custom lando command, to sync Drupal db with updates, config changes in codebase.
  bup:
    service: appserver
    description: Branch update (run composer / db updates / import config / clear caches).
    cmd:
      - composer install
      - drush cr
      - drush updb
      - drush cim -y
      - drush cr
