<?php

/**
 * @file
 * Preprocess function for page.
 */

/**
 * Implements hook_theme_suggestion_HOOK_alter().
 */
function vote_nvrf_theme_suggestions_page_alter(array &$suggestions, array $variables) {
  $current_route_name = \Drupal::routeMatch()->getRouteName();

  // Custom route.
  if ($current_route_name == 'vote_nvrf.nvrf_page') {
    $suggestions[] = "page__node__" . str_replace('.', '_', $current_route_name);
  }
}
