# https://docs.lando.dev/
# UPDATE: name property should be unique name for project.
name: vote-gov
recipe: drupal10
# Define services, remove any services your project doesn't need.
# https://docs.lando.dev/config/services.html#supported-services
config:
  php: '8.2'
  composer_version: '2.5.5'
  database: mysql:8.0
  # Adjust this to point to directory where index.php exist.
  webroot: web
  # Make false if you need better performance and don't need to use XDebug.
  xdebug: false
# https://docs.lando.dev/config/events.html#usage
# Can setup proxy urls to your services.
# https://docs.lando.dev/config/proxy.html
services:
  node:
    type: "node:18"
    scanner: false
    ssl: true
    sslExpose: false
    build_as_root:
      - apt update -y && apt-get install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb -y
    build:
      - npm install --prefix /app/testing && npm install -g cypress@12.9.0
    overrides:
      ports:
        - "32654:32654"
  appserver:
    # Point to custom development php.ini
    config:
      php: '.lando/config/php.ini'
    overrides:
      environment:
        DRUSH_OPTIONS_ROOT: '/app/web'
        # UPDATE: to the same as the name key above.
        DRUSH_OPTIONS_URI: 'http://vote-gov.lndo.site'
        # Adding this variable for PHPStorm
        PHP_IDE_CONFIG: "serverName=appserver"
        cypress_random_pass: "password"
  tome:
    type: apache
    webroot: html
#  pma:
#    type: phpmyadmin
#    hosts:
#      - database
proxy:
  # custom proxy for static site files generated by tome.
  tome:
    - html.vote-gov.lndo.site
#  pma:
#    # UPDATE: to the same as the name key above.
#    - pma.vote-gov.lndo.site
# Setup tooling so when you type lando keyword
# it knows the service to use.
# https://docs.lando.dev/config/tooling.html#usage
tooling:
  coder-sniffer:
    cmd: '/app/vendor/squizlabs/php_codesniffer/bin/phpcs --ignore=*/node_modules/* --standard=/app/vendor/drupal/coder/coder_sniffer/Drupal,vendor/drupal/coder/coder_sniffer/DrupalPractice --extensions=php,module,inc,theme,info,yml,twig --report=full /app/web/modules/custom /app/web/themes/custom -n'
    service: appserver
  npm-testing:
    service: node
    description: Used for npm <commands>
    cmd: npm --prefix  /app/testing
  npm-theme:
    service: node
    description: Runs npm commands
    cmd: npm --prefix  /app/web/themes/custom/vote_gov
  gulp:
    service: node
    dir: "/app/web/themes/custom/vote_gov"
    cmd: npm run gulp --prefix  /app/web/themes/custom/vote_gov
  gulp-compile:
    service: node
    dir: "/app/web/themes/custom/vote_gov"
    cmd: npm run build --prefix  /app/web/themes/custom/vote_gov
  # Custom lando command, to sync Drupal db with updates, config changes in codebase.
  'cy:axe':
    service: node
    cmd: npm run cy:axe --prefix /app/testing
    description: run cypress accessibility test - headless
  'cy:links':
    service: node
    cmd: npm run cy:links --prefix /app/testing
    description: run cypress internal links tess - headless
  'cy:proofer':
    service: node
    cmd:  npm run cy:proofer --prefix /app/testing
    description: run cypress external links test - headless
  'cy:test':
    service: node
    cmd:  npm run cy:test --prefix /app/testing
    description: run cypress functional tests - headless
  'cy:testSuite':
    service: node
    cmd:  npm run cypress run --prefix /app/testing
    description: run full testing suite, functional, internal links, external links and accessibility - headless
  retune:
    service: appserver
    description: Branch update (run composer / db updates / import config / clear caches).
    cmd:
      - composer install
      - drush cr
      - drush updb
      - drush cim -y
      - drush locale-check
      - drush locale-update
      - drush cr
  import-translations:
    service: appserver
    description: Import string translations from vote_utility module
    cmd:
      - drush locale-check
      - drush locale-update
      - drush cr
  set:
    service: appserver
    description: Creates a settings.local file
    cmd:
      - cp /app/.lando/settings.local.php /app/web/sites
      - cp /app/.lando/services.local.yml /app/web/sites
      - drush cr
  static:
    service: appserver
    description: Manually recompiles static site and assets
    cmd:
      - drush tome:static --uri=http://html.vote-gov.lndo.site
  xoff:
    cmd: "rm /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && /etc/init.d/apache2 reload"
    description: Disable xdebug.
    service: appserver
    user: root
  xon:
    cmd: "docker-php-ext-enable xdebug && /etc/init.d/apache2 reload"
    description: Enable xdebug.
    service: appserver
    user: root
events:
  post-set:
    - echo "Successfully enabled local development settings and services files!"
  pre-db-import:
    # Fix MySQL 8 import issue (dropping DB with Drush). https://github.com/lando/lando/issues/2679
    - appserver: echo "Dropping the DB with Drush" && drush sql:drop -y
