# https://docs.lando.dev/
# UPDATE: name property should be unique name for project.
name: vote-gov
recipe: drupal10
# Define services, remove any services your project doesn't need.
# https://docs.lando.dev/config/services.html#supported-services
config:
  # Adjust this to point to directory where index.php exist.
  webroot: web
  # Make false if you need better performance and don't need to use XDebug.
  xdebug: false
# https://docs.lando.dev/config/events.html#usage
# Can setup proxy urls to your services.
# https://docs.lando.dev/config/proxy.html
services:
#  node:
#    type: "node:18"
#    scanner: false
#    ssl: true
#    sslExpose: false
#    overrides:
#      ports:
#        - "32654:32654"
  appserver:
    # Point to custom development php.ini
    config:
      php: '.lando/config/php.ini'
    overrides:
      environment:
        DRUSH_OPTIONS_ROOT: '/app/web'
        # UPDATE: to the same as the name key above.
        DRUSH_OPTIONS_URI: 'http://vote-gov.lndo.site'
        # Adding this variable for PHPStorm
        PHP_IDE_CONFIG: "serverName=appserver"
  tome:
    type: apache
    webroot: html
  pma:
    type: phpmyadmin
    hosts:
      - database
proxy:
  # custom proxy for static site files generated by tome.
  tome:
    - html.vote-gov.lndo.site
  pma:
    # UPDATE: to the same as the name key above.
    - pma.vote-gov.lndo.site
# Setup tooling so when you type lando keyword
# it knows the service to use.
# https://docs.lando.dev/config/tooling.html#usage
tooling:
#  npm:
#    service: node
#    description: Runs npm commands
#    cmd: npm --prefix  /app/web/themes/custom/vote_gov
#  gulp:
#    service: node
#    dir: "/app/web/themes/custom/vote_gov"
#    cmd: npm run gulp --prefix  /app/web/themes/custom/vote_gov
#  gulp-compile:
#    service: node
#    dir: "/app/web/themes/custom/vote_gov"
#    cmd: npm run build --prefix  /app/web/themes/custom/vote_gov
  # Custom lando command, to sync Drupal db with updates, config changes in codebase.
  retune:
    service: appserver
    description: Branch update (run composer / db updates / import config / clear caches).
    cmd:
      - composer install
      - drush cr
      - drush updb
      - drush cim -y
      - drush cr
  set:
    service: appserver
    description: Creates a settings.local file
    cmd:
      - cp /app/.lando/settings.local.php /app/web/sites
      - cp /app/.lando/services.local.yml /app/web/sites
      - drush cr
  xoff:
    cmd: "rm /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && /etc/init.d/apache2 reload"
    description: Disable xdebug.
    service: appserver
    user: root
  xon:
    cmd: "docker-php-ext-enable xdebug && /etc/init.d/apache2 reload"
    description: Enable xdebug.
    service: appserver
    user: root
events:
  post-set:
    - echo "Successfully enabled local development settings and services files!"
