# https://docs.lando.dev/
# UPDATE: name property should be unique name for project.
name: vote-gov
recipe: drupal10
# Define services, remove any services your project doesn't need.
# https://docs.lando.dev/config/services.html#supported-services
config:
  php: '8.3'
  composer_version: '2.7.7'
  database: mysql:8.0
  # Adjust this to point to directory where index.php exist.
  webroot: web
  # Make false if you need better performance and don't need to use XDebug.
  xdebug: false
# https://docs.lando.dev/config/events.html#usage
# Can setup proxy urls to your services.
# https://docs.lando.dev/config/proxy.html
services:
  appserver:
    # Point to custom development php.ini
    config:
      php: '.lando/config/php.ini'
    overrides:
      environment:
        DRUSH_OPTIONS_ROOT: '/app/web'
        # UPDATE: to the same as the name key above.
        DRUSH_OPTIONS_URI: 'http://vote-gov.lndo.site'
        # Adding this variable for PHPStorm
        PHP_IDE_CONFIG: "serverName=appserver"
        cypress_random_pass: "password"
  tome:
    type: apache
    webroot: html
#  pma:
#    type: phpmyadmin
#    hosts:
#      - database
proxy:
  # custom proxy for static site files generated by tome.
  tome:
    - html.vote-gov.lndo.site
#  pma:
#    # UPDATE: to the same as the name key above.
#    - pma.vote-gov.lndo.site
# Setup tooling so when you type lando keyword
# it knows the service to use.
# https://docs.lando.dev/config/tooling.html#usage
tooling:
  phplint:
    cmd: '/app/vendor/squizlabs/php_codesniffer/bin/phpcs --ignore=*/node_modules/* --standard=/app/vendor/drupal/coder/coder_sniffer/Drupal,vendor/drupal/coder/coder_sniffer/DrupalPractice --extensions=php,module,inc,theme,info,yml,twig --report=full /app/web/modules/custom /app/web/themes/custom -n'
    service: appserver
  # Custom lando command, to sync Drupal db with updates, config changes in codebase.
  retune:
    service: appserver
    description: Branch update (run composer / db updates / import config / clear caches).
    cmd:
      - composer install
      - drush cr
      - drush updb
      - drush cim -y
      - drush locale-check
      - drush locale-update
      - drush cr
  import-translations:
    service: appserver
    description: Import string translations from vote_utility module
    cmd:
      - drush locale-check
      - drush locale-update
      - drush cr
  set:
    service: appserver
    description: Creates a settings.local file
    cmd:
      - cp /app/.lando/settings.local.php /app/web/sites
      - cp /app/.lando/services.local.yml /app/web/sites
      - drush cr
  static:
    service: appserver
    description: Manually recompiles static site and assets
    cmd:
      - drush tome:static --uri=http://html.vote-gov.lndo.site
  xoff:
    cmd: "rm /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && /etc/init.d/apache2 reload"
    description: Disable xdebug.
    service: appserver
    user: root
  xon:
    cmd: "docker-php-ext-enable xdebug && /etc/init.d/apache2 reload"
    description: Enable xdebug.
    service: appserver
    user: root
events:
  post-set:
    - echo "Successfully enabled local development settings and services files!"
  pre-db-import:
    # Fix MySQL 8 import issue (dropping DB with Drush). https://github.com/lando/lando/issues/2679
    - appserver: echo "Dropping the DB with Drush" && drush sql:drop -y
