<?php

/**
 * @file
 * The module file with theming functions.
 */

/**
 * Implements hook_theme().
 */
function ec_placeholder_theme($existing, $type, $theme, $path) {
  return [
    'ec_placeholder' => [
      'variables' => [
        'machine_name' => NULL,
      ],
      'template' => 'embedded-content/ec-placeholder',
    ],
  ];
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function ec_placeholder_theme_suggestions_ec_placeholder(array $variables) {
  $suggestions = [];
  $sanitized_machine_name = str_replace([' ', '-'], '_', strtolower($variables['machine_name']));
  $suggestions[] = 'ec_placeholder__' . $sanitized_machine_name;

  return $suggestions;
}
