tags:
  description: 'Hait&#39;1o i&#39;ii&#39;n77[ biniiy4 hazh&#39;dii[&#39;88h7g77 han7t1h [current-page:title]'
  title: 'An1&#39;1&#39;ah7 B1 Hada&#39;dilne&#39; [current-page:title] biyi&#39; | [site:name] Diné'
