<?php

/**
 * @file
 * Functions to support theme templates.
 */

require_once dirname(__FILE__) . '/preprocess/global.inc';
require_once dirname(__FILE__) . '/preprocess/form.inc';
require_once dirname(__FILE__) . '/preprocess/navigation.inc';
require_once dirname(__FILE__) . '/preprocess/taxonomy.inc';
require_once dirname(__FILE__) . '/preprocess/user.inc';
require_once dirname(__FILE__) . '/preprocess/views.inc';
