adding:
  dependencies:
    module:
      - disable_language
  permissions:
    - 'create content in disabled language'
    - 'view disabled languages'
removing:
  dependencies:
    module:
      - field_ui
      - views_ui
