adding:
  dependencies:
    module:
      - devel
      - disable_language
  permissions:
    - 'access devel information'
    - 'create content in disabled language'
    - 'view disabled languages'
removing: {  }
