_core:
  default_config_hash: uEePITI9tV6WqzmsTb7MfPCi5yPWXSxAN1xeLcYFQbM
session:
  parameter: language
url:
  source: path_prefix
  prefixes:
    en: ''
    es: es
    ko: ko
    tl: tl
    bn: bn
    zh-hans: zh-hans
    zh: zh
    hi: hi
    km: km
    nv: nv
    vi: vi
    ypk: ypk
    '': null
    ru: ru
  domains:
    en: ''
    es: ''
    ko: ''
    tl: ''
    bn: ''
    zh-hans: ''
    zh: ''
    hi: ''
    km: ''
    nv: ''
    vi: ''
    ypk: ''
    ru: ''
selected_langcode: site_default
