entity_type_groups:
  node:
    landing:
      basic: basic
      open_graph: open_graph
      twitter_cards: twitter_cards
    page:
      basic: basic
      open_graph: open_graph
      twitter_cards: twitter_cards
    state_territory:
      basic: basic
      open_graph: open_graph
      twitter_cards: twitter_cards
tag_trim_method: beforeValue
tag_trim_maxlength:
  metatag_maxlength_abstract: null
  metatag_maxlength_description: null
  metatag_maxlength_title: null
  metatag_maxlength_og_description: null
  metatag_maxlength_og_site_name: null
  metatag_maxlength_og_title: null
  metatag_maxlength_twitter_cards_description: null
  metatag_maxlength_twitter_cards_label1: null
  metatag_maxlength_twitter_cards_label2: null
  metatag_maxlength_twitter_cards_title: null
tag_scroll_max_height: ''
