#!/bin/bash

home="/home/vcap"
app_path="${home}/app"
html_path="${app_path}/html"

source ${home}/.bashrc

mkdir -p ${html_path}

export PYTHONWARNINGS="ignore:Unverified HTTPS request"

export application_uri=$(echo $VCAP_APPLICATION | jq -r '.application_uris[]')

export AWS_ACCESS_KEY_ID=$(echo $VCAP_SERVICES | jq -r '.s3[] | select(.name | strings | test("static")).credentials.access_key_id')
export AWS_SECRET_ACCESS_KEY=$(echo $VCAP_SERVICES | jq -r '.s3[] | select(.name | strings | test("static")).credentials.secret_access_key')
export AWS_DEFAULT_REGION=$(echo $VCAP_SERVICES | jq -r '.s3[] | select(.name | strings | test("static")).credentials.region')

export bucket_name=$(echo $VCAP_SERVICES | jq -r '.s3[] | select(.name | strings | test("static")).name')
export bucket=$(echo $VCAP_SERVICES | jq -r '.s3[] | select(.name | strings | test("static")).credentials.bucket')
export bucket_endpoint=$(echo $VCAP_SERVICES | jq -r '.s3[] | select(.name | strings | test("static")).credentials.endpoint')

export external_endpoint="https://ssg-${ENV}.vote.gov"
[ "${ENV}" = "prod" ] && export external_endpoint="https://ssg.vote.gov"

cd ${app_path}
echo "Running 'drush tome:static' in '${ENV}'..."
drush tome:static --uri=${external_endpoint} --process-count=2 --retry-count=0 -y
echo "'drush tome:static' task completed!"

cd ${html_path}
echo "Copying static files to '${bucket_name}'..."
aws s3 sync . s3://${bucket} --delete --no-verify-ssl 2>/dev/null
aws s3 website s3://${bucket} --index-document index.html --error-document /404/index.html  --no-verify-ssl 2>/dev/null
echo "Copy to '${bucket_name}' completed!"

export objects=($(aws s3 ls ${bucket} --recursive --no-verify-ssl 2>/dev/null | awk '{print $(NF)}' | sed -z -e 's/\n/ /g'))

for object in "${objects[@]}"; do
  echo $object
  aws s3api put-object-acl --bucket ${bucket} --key $object --grant-full-control id=c0eaf99010b9e4b073052b3a9b242980a2badf4e1db4044f53f49950609bf6cf --grant-read uri=http://acs.amazonaws.com/groups/global/AllUsers --no-verify-ssl 2>/dev/null
done