#!/bin/bash

export application_uri=$(echo $VCAP_APPLICATION | jq -r '.application_uris[]')

while true
do
  echo "Running 'drush cron'..."
  drush --root=$HOME/web core:cron --uri=https://${application_uri}
  echo "'drush cron' task completed!"
  sleep 60m
done

while true
do
  echo "Running 'drush tome:static'..."
  s3_uri=$(echo $VCAP_SERVICES | jq -r '.s3[] | select(.name | contains("static")).credentials.uri')
  drush --root=$HOME/web tome:static --uri https://vote-waf-test.app.cloud.gov --process-count=1
  echo "'drush cron' task completed!"
  sleep 30m
done
