#!/bin/bash

export application_uri=$(echo $VCAP_APPLICATION | jq -r '.application_uris[]')

while true
do
  echo "Running 'drush cron'..."
  drush --root=$HOME/web core:cron --uri=https://${waf_external_endpoint}
  echo "'drush cron' task completed!"
  sleep 60m
done
